// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh3dRa39itBXX3_bA5qb_m6LGQJRFKo3M',
    appId: '1:805961120538:web:f1f6cd82b36d28f3bf0aa3',
    messagingSenderId: '805961120538',
    projectId: 'music-room-app-a65c7',
    authDomain: 'music-room-app-a65c7.firebaseapp.com',
    storageBucket: 'music-room-app-a65c7.firebasestorage.app',
    measurementId: 'G-6F49YTN9LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWD8YyRgb9mFzH9htd6VRCWBIZ1E14cLI',
    appId: '1:805961120538:android:aa9cc589816ca61cbf0aa3',
    messagingSenderId: '805961120538',
    projectId: 'music-room-app-a65c7',
    storageBucket: 'music-room-app-a65c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADvsD02q9XWYnonl2f4Cz65bCp1IDkcOw',
    appId: '1:805961120538:ios:b3b8ecd4572f1634bf0aa3',
    messagingSenderId: '805961120538',
    projectId: 'music-room-app-a65c7',
    storageBucket: 'music-room-app-a65c7.firebasestorage.app',
    iosBundleId: 'com.musicroom.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADvsD02q9XWYnonl2f4Cz65bCp1IDkcOw',
    appId: '1:805961120538:ios:b3b8ecd4572f1634bf0aa3',
    messagingSenderId: '805961120538',
    projectId: 'music-room-app-a65c7',
    storageBucket: 'music-room-app-a65c7.firebasestorage.app',
    iosBundleId: 'com.musicroom.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh3dRa39itBXX3_bA5qb_m6LGQJRFKo3M',
    appId: '1:805961120538:web:64f097e861caeb10bf0aa3',
    messagingSenderId: '805961120538',
    projectId: 'music-room-app-a65c7',
    authDomain: 'music-room-app-a65c7.firebaseapp.com',
    storageBucket: 'music-room-app-a65c7.firebasestorage.app',
    measurementId: 'G-32BM1VCNEW',
  );
}
